### ISSUE TITLE
500 error when setting status on assignments

### ISSUE THREAD

**Issue by espenak** [devilry/trix#1]
I think this is the following error from the server log:

```
NameError at /trix/exercise/10/status
global name 'get_level' is not defined
/trix/devilrybuild/src/trix/trix/views/ajaxviews.py in exercisestatus
42:    points = get_level(get_points(request.user))
```

**Comment by siriamj** [comment]
Error still there. Context: Log in, browse periods and select, try to change status on one of the exercises shown.

![image](https://f.cloud.github.com/assets/1157577/1608598/5b82c822-5507-11e3-9438-9fd52cf7a420.png)

**Comment by espenak** [comment]
Looks like the change in 389bdd9a6d827511d6379f32fab608460f2228bb fixed this. I have not been able to reproduce this locally because I can not find the UI to assign Exercises to Periods, but I updated the IFI instance, and it seems to work.
