### ISSUE TITLE
Service unavailable!

### ISSUE THREAD

**Issue by siriamj** [devilry/trix#7]

**Comment by tworide** [comment]
Kan se ut som om serveren til IFI er nede.

2014-04-10 12:19 GMT+02:00 siriamj notifications@github.com:

> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/devilry/trix/issues/7
> .

## 

Med vennlig hilsen

Tor Ivar Johansen
torivar.johansen@gmail.com
