### ISSUE TITLE
Permalinks restricted to a single tag

### ISSUE THREAD

**Issue by HenrikLovold** [devilry/trix#8]
When creating a permalink, every but the first tag specified get deleted. For instance, creating a permalink to the tags:

inf1000, host2014, uke1

Gives a link to all tasks with the tag "inf1000", and removes the "host2014, uke1" tags.

**Comment by torgeirl** [comment]
Direct links to single assignments will be added in `v2.1.0`: https://github.com/devilry/trix2/issues/33
